language: go
go:
- '1.13'

deploy:
  provider: releases
  api_key:
    secure: vdBQReWvcS6D77uuq3CBHUEN8LfUU1u0Au1sKAWpAcnY67lSKMwNFusKDk51JAQWLMUz5u2jEXWt/yjeuHMQJHZTDUj6lOAJeNIU1cMTSsES0xPhIN3CwuHjHWOJ3aL0i31Kg889/VKo/cEBpSHFgzkribtIi1yf8cuZiG2wNG8KR+V/PqOBDgCyZ3SWuG9dXwnfJIqiYt4x1BrurTfdSBrOdspRb8rPz0WJNQSOBH3FG/3X1l2O/c5RxzjYfdtFLEM10Ey3VmJBqj0aFh+nwirHKZUgD88bpgeWSZ21zk8yUvZcUPh3YoJKF7eN1ZkCjChQ8IgYs3WIirOebV3//N/AICQ7aPbFsjrZW7z6Z6MELzzNz3r395yzlTzqMUp1heFiWYey2zjgYSSZ7zIiZO+aV6cgyvsJHBnfO6SOn/kOMK385EzSkpuXa/MHOvntgdt7W+Ii/m8F3BHsaGMXIROiVPRKxSTYgthjlsSgiYiSsMXID0bhW6pRxRsDJROkfuudmRfmEneXNH1Gc/DWO/PXrINQTo4TIBfLSgSoEYynfaumOdXp4s1j3h9xF5EtfEAvZi5ylFdQKUyDeiEfp3E+O2sk8dfTgkUdOctZbhCMvA/4BThm89JzJiVLkdHbEx7jr4X47mcc5/yUxiPolwswfTZhzNbi4wc+gWMEAGA=
  file: bin/terraform-provider-pact
  on:
    repo: pactflow/terraform
