on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go-version: [1.15.x]
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.5
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make
      env:
        PACT_BROKER_TOKEN: '${{ secrets.PACT_BROKER_TOKEN }}'